[package]
name = "focustree"
version = "0.1.0"
cairo-version = "2.2.0"
authors = [
    "Gabin Marignier <gabin@focustree.app>",
    "Paul Reboullet paul@focustree.app"
]
description = "Focus Tree Contracts written in Cairo for StarkNet"
readme = "README.md"
repository = "https://github.com/focustree/contracts"
license-file = "LICENSE"
keywords = ["focustree", "starknet", "cairo", "contracts"]

[dependencies]
starknet = ">=2.2.0"

[lib]

[[target.starknet-contract]]
sierra = true
casm = false
