#!/bin/zsh
ACCOUNT_SIERRA_PATH=./target/dev/focustree_FocusAccount.sierra.json

if [[ $1 == "declare" ]]; then
    scarb build
    starkli declare $ACCOUNT_SIERRA_PATH
elif [[ $1 == "fetch" ]]; then
    starkli account fetch $STARKNET_ACCOUNT_ADDRESS > .starkli/$2         
else 
    echo "Available commands: declare, fetch";
fi;